"""Drop to colunm from notifications

Revision ID: 055fb9af2dbc
Revises: ab18c35fdf49
Create Date: 2025-10-25 14:08:42.668564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '055fb9af2dbc'
down_revision: Union[str, None] = 'ab18c35fdf49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_to'), table_name='notifications')
    op.drop_column('notifications', 'to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('to', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_notifications_to'), 'notifications', ['to'], unique=False)
    # ### end Alembic commands ###
