"""Update camera areas add options

Revision ID: 05efc465045a
Revises: 6dec6594f228
Create Date: 2025-07-16 10:21:53.960082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '05efc465045a'
down_revision: Union[str, None] = '6dec6594f228'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('camera_areas', sa.Column('options', sa.JSON(), nullable=True, default=None))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('camera_areas', 'options')
    # ### end Alembic commands ###
