"""Update cameras DROP record_mode

Revision ID: 1f96f2db828c
Revises: c45608210952
Create Date: 2025-06-30 18:28:24.678264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '1f96f2db828c'
down_revision: Union[str, None] = 'c45608210952'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'record_duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('record_duration', sa.INTEGER(), nullable=False))
    # ### end Alembic commands ###
