"""Add plugin ID to devices

Revision ID: baf4ddbd4733
Revises: 6be1dadc3552
Create Date: 2026-07-09 18:40:16.104801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'baf4ddbd4733'
down_revision: Union[str, None] = '6be1dadc3552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('plugin_id', sa.Integer(), nullable=False))
    op.create_foreign_key('devices_plugin_id_fkey', 'devices', 'plugins', ['plugin_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('devices_plugin_id_fkey', 'devices', type_='foreignkey')
    op.drop_column('devices', 'plugin_id')
    # ### end Alembic commands ###
