"""Add is_core to plugins

Revision ID: 21623384e939
Revises: 2a21cdc4a88d
Create Date: 2026-07-01 10:05:31.370232

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '21623384e939'
down_revision: Union[str, None] = '2a21cdc4a88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugins', sa.Column('is_core', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.create_index(op.f('ix_plugins_is_core'), 'plugins', ['is_core'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_plugins_is_core'), table_name='plugins')
    op.drop_column('plugins', 'is_core')
    # ### end Alembic commands ###
