"""Add string type to device

Revision ID: 260b69e913e7
Revises: c3145382fd17
Create Date: 2026-03-09 21:19:47.295655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '260b69e913e7'
down_revision: Union[str, None] = 'c3145382fd17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'type',
               existing_type=sa.INTEGER(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'type',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
