"""Add feature to devices

Revision ID: 2a21cdc4a88d
Revises: 7c618b3aaf35
Create Date: 2026-04-12 09:53:03.248324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '2a21cdc4a88d'
down_revision: Union[str, None] = '7c618b3aaf35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('feature', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_devices_feature'), 'devices', ['feature'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_feature'), table_name='devices')
    op.drop_column('devices', 'feature')
    # ### end Alembic commands ###
