"""Add external_id to devices

Revision ID: 2ccd748d0b76
Revises: 847c312a2f2e
Create Date: 2026-03-10 21:08:48.534963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '2ccd748d0b76'
down_revision: Union[str, None] = '847c312a2f2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_devices_external_id'), 'devices', ['external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_external_id'), table_name='devices')
    op.drop_column('devices', 'external_id')
    # ### end Alembic commands ###
