"""Add capabilities to device

Revision ID: 602342c20c3b
Revises: 260b69e913e7
Create Date: 2026-03-10 12:42:11.555148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '602342c20c3b'
down_revision: Union[str, None] = '260b69e913e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('capabilities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'capabilities')
    # ### end Alembic commands ###
