"""Update devices - remove feature, source and add index unique external_id

Revision ID: 6be1dadc3552
Revises: 21623384e939
Create Date: 2026-07-09 18:12:05.784114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '6be1dadc3552'
down_revision: Union[str, None] = '21623384e939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_feature'), table_name='devices')
    op.drop_index(op.f('ix_devices_source'), table_name='devices')
    op.drop_index(op.f('ix_devices_external_id'), table_name='devices')
    op.create_index(op.f('ix_devices_external_id'), 'devices', ['external_id'], unique=True)
    op.drop_column('devices', 'source')
    op.drop_column('devices', 'feature')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('feature', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_devices_external_id'), table_name='devices')
    op.create_index(op.f('ix_devices_external_id'), 'devices', ['external_id'], unique=False)
    op.create_index(op.f('ix_devices_source'), 'devices', ['source'], unique=False)
    op.create_index(op.f('ix_devices_feature'), 'devices', ['feature'], unique=False)
    # ### end Alembic commands ###
