"""Update devices add source field

Revision ID: 6d5f3bc48e6a
Revises: a035f648e114
Create Date: 2025-11-30 17:47:24.349659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '6d5f3bc48e6a'
down_revision: Union[str, None] = 'a035f648e114'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_devices_source'), 'devices', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_source'), table_name='devices')
    op.drop_column('devices', 'source')
    # ### end Alembic commands ###
