"""Update cameras ADD record_mode

Revision ID: 6dec6594f228
Revises: 1f96f2db828c
Create Date: 2025-06-30 18:28:43.760340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '6dec6594f228'
down_revision: Union[str, None] = '1f96f2db828c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('record_duration', sa.INTEGER, nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'record_duration')
    # ### end Alembic commands ###
