"""Alter device_sensors

Revision ID: 7c618b3aaf35
Revises: 2ccd748d0b76
Create Date: 2026-04-11 12:55:53.780783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '7c618b3aaf35'
down_revision: Union[str, None] = '2ccd748d0b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_sensors', sa.Column('unit', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('device_sensors', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device_sensors', 'icon')
    op.drop_column('device_sensors', 'unit')
    # ### end Alembic commands ###
