"""Add identifier field to sensors

Revision ID: 847c312a2f2e
Revises: 602342c20c3b
Create Date: 2026-03-10 18:54:54.494688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel
# revision identifiers, used by Alembic.
revision: str = '847c312a2f2e'
down_revision: Union[str, None] = '602342c20c3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_sensors', sa.Column('identifier', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.drop_constraint(op.f('uq_device_id_capability'), 'device_sensors', type_='unique')
    op.create_unique_constraint('uq_device_id_cap_ident', 'device_sensors', ['device_id', 'capability', 'identifier'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_device_id_cap_ident', 'device_sensors', type_='unique')
    op.create_unique_constraint(op.f('uq_device_id_capability'), 'device_sensors', ['device_id', 'capability'], postgresql_nulls_not_distinct=False)
    op.drop_column('device_sensors', 'identifier')
    # ### end Alembic commands ###
