"""Add online to camera table

Revision ID: ab18c35fdf49
Revises: 6d403cdf4fa0
Create Date: 2025-10-17 18:07:11.782218

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'ab18c35fdf49'
down_revision: Union[str, None] = '6d403cdf4fa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('cameras', sa.Column('online', sa.Boolean(),
                                       server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_cameras_online'), 'cameras', ['online'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cameras_online'), table_name='cameras')
    op.drop_column('cameras', 'online')
    # ### end Alembic commands ###
