"""add key to rule_nodes

Revision ID: adfad3693aee
Revises: a38a58dce7c0
Create Date: 2025-08-19 17:57:43.473615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'adfad3693aee'
down_revision: Union[str, None] = 'a38a58dce7c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rule_nodes', sa.Column('type', sa.Enum('TRIGGER', 'CONDITION', 'ENTITY', 'ACTION', 'START', 'END', name='rulenodetypes'), nullable=True))
    op.add_column('rule_nodes', sa.Column('key', sa.Enum('RULE_START', 'RULE_END', 'SENSORS_CHANGES', 'DEVICES_CHANGES', 'MOTION_START', 'MOTION_END', 'ALARM_ON', 'ALARM_OFF', 'ACTION_EMAIL', 'ACTION_TELEGRAM', 'ACTION_WEBHOOK', name='rulenodetypekeys'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rule_nodes', 'key')
    op.drop_column('rule_nodes', 'type')
    # ### end Alembic commands ###
