"""Create rules table

Revision ID: b776cdd8c211
Revises: 
Create Date: 2025-08-24 00:24:16.299434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'b776cdd8c211'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('updated', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_nodes',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('key', sa.Enum('RULE_START', 'RULE_END', 'RULE_CONDITION', 'SENSORS_CHANGES', 'DEVICES_CHANGES', 'MOTION_START', 'MOTION_END', 'ACTION_CAMERA', 'ACTION_DEVICE', 'ENTITIES_SENSOR', 'ACTION_ALARM_ON', 'ACTION_ALARM_OFF', 'ACTION_EMAIL', 'ACTION_TELEGRAM', 'ACTION_WEBHOOK', 'ACTION_SCREENSHOT', 'ACTION_RECORD_START', name='rulenodetypekeys'), nullable=True),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.Enum('DEVICE', 'SENSOR', 'CAMERA', name='ruleentitytype'), nullable=True),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rule_edges',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('source_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['rule_id'], ['rules.id'], ),
    sa.ForeignKeyConstraint(['source'], ['rule_nodes.id'], ),
    sa.ForeignKeyConstraint(['target'], ['rule_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rule_edges')
    op.drop_table('rule_nodes')
    op.drop_table('rules')
    # ### end Alembic commands ###
