"""Delete Identifier from sensors

Revision ID: ba65355b72f8
Revises: 56560af32ed6
Create Date: 2026-03-09 17:42:52.652780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


import sqlmodel
# revision identifiers, used by Alembic.
revision: str = 'ba65355b72f8'
down_revision: Union[str, None] = '56560af32ed6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_sensors', sa.Column('capability', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_index(op.f('ix_device_sensors_identifier'), table_name='device_sensors')
    op.create_index(op.f('ix_device_sensors_capability'), 'device_sensors', ['capability'], unique=False)
    op.create_unique_constraint('uq_device_id_capability', 'device_sensors', ['device_id', 'capability'])
    op.drop_column('device_sensors', 'identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_sensors', sa.Column('identifier', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_device_id_capability', 'device_sensors', type_='unique')
    op.drop_index(op.f('ix_device_sensors_capability'), table_name='device_sensors')
    op.create_index(op.f('ix_device_sensors_identifier'), 'device_sensors', ['identifier'], unique=True)
    op.drop_column('device_sensors', 'capability')
    # ### end Alembic commands ###
