"""Add active field to sensors

Revision ID: c3145382fd17
Revises: ba65355b72f8
Create Date: 2026-03-09 21:08:27.933945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel
from sqlalchemy import true

# revision identifiers, used by Alembic.
revision: str = 'c3145382fd17'
down_revision: Union[str, None] = 'ba65355b72f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device_sensors', sa.Column('active', sa.Boolean(), nullable=False, server_default=true()))
    op.create_index(op.f('ix_device_sensors_active'), 'device_sensors', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_device_sensors_active'), table_name='device_sensors')
    op.drop_column('device_sensors', 'active')
    # ### end Alembic commands ###
