"""Update cameras add alerts

Revision ID: c45608210952
Revises: e311aaf29fb9
Create Date: 2025-06-30 13:56:19.756981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c45608210952'
down_revision: Union[str, None] = 'e311aaf29fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cameras', sa.Column('alerts', sa.Boolean, server_default=sa.text('0'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cameras', 'alerts')
    # ### end Alembic commands ###
